#!/usr/bin/env bash

set -eu

CONFIGS=( $(ls conf) )
WORK=false

install_vim_vundle() {
  if ! [[  -d "${HOME}/.vim/bundle/Vundle.vim" ]]; then
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  fi
}

sym_link() {
  echo "ln -s \"${1}\" \"${2}\""
  ln -s "${1}" "${2}"
}

noisy_link() {
  echo "ln \"${1}\" \"${2}\""
  ln "${1}" "${2}"
}

check_link() {
  if ! [[ -e ${2} ]]; then
    noisy_link "${1}" "${2}"
  else
    # check if the item has 2 links to it,
    # indictating it is a file that has a hard link to it
    if [[ $(stat --format '%h' "${2}") -eq 2 ]]; then
      echo "linked:skipped: ${2}"
    # If file exists
    elif [[ -e "${2}" ]]; then
      echo "not-linked:exists:skipped: rm -rf ${2}"
    fi
  fi
}

check_sym_link() {
  if ! [[ -e ${2} ]]; then
    sym_link "${1}" "${2}"
  elif [[ -L ${2} ]];then
    echo "linked:skipped: ${2}"
  else
    echo "not-linked:exists:skipped: rm -rf ${2}"
  fi
}

oh_my_zsh() {
  if ! [[ -d "${HOME}/.oh-my-zsh" ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi
}

vim_setup() {
  install_vim_vundle
  mkdir -p "${HOME}"/.vim/colors
  vim +PluginInstall +qall

  if [[ -f "${HOME}"/.vim/bundle/vim-colorschemes/colors/* ]]; then
   mv "${HOME}"/.vim/bundle/vim-colorschemes/colors/* \
    "${HOME}"/.vim/colors
  fi

  if [[ -f "${HOME}"/.vim/bundle/vim-railscasts-theme/colors/* ]]; then
    mv "${HOME}"/.vim/bundle/vim-railscasts-theme/colors/* \
      "${HOME}"/.vim/colors
  fi
}

work_check() {
  read -r -p "Work machine (y/n)? " choice
  case "$choice" in 
    y|Y ) WORK=true;;
    n|N ) WORK=false;;
    * ) work_check;;
  esac
}

main() {
  # Ask if this is my work machine
  work_check
  oh_my_zsh

  # Hard link all config files
  for i in "${CONFIGS[@]}"; do
    if [[ "${i}" == *"greg-kman.zsh-theme"* ]]; then
      check_link  "conf/${i}" "${HOME}/.oh-my-zsh/themes/greg-kman.zsh-theme"
      continue
    fi
    check_link "conf/${i}" "${HOME}/.${i}"
  done

  vim_setup
  check_sym_link "${PWD}/bin" "${HOME}/bin"

  if $WORK; then
    grep -qxF 'source ~/.zshrc-work' conf/zshrc || echo 'source ~/.zshrc-work' >> conf/zshrc
  fi
  source ~/.zshrc
}

main
