theme = "dracula"

# catppuccin_mocha
# new_moon
# night_owl
# noctis
# nord-night
# rasmus
# solarized_dark
# sonokai
# tokyonight_moon
# tokyonight_storm
# iroaseta
# darcula-solid
# jetbrains dark
# seoul 256 dark hard
