export SHOW_AWS_PROMPT=false
export ZSH=~/.oh-my-zsh
export GOPATH=~/code/gocode
export PATH=$PATH:~/bin:~/code/gocode/bin
# autoload -U colors && colors
# autoload -U promptinit
# promptinit

##
## Alias finder
##
zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes # disabled by default

##
## AWS
##
export AWS_PAGER=""

###
### TODO
###
# ## turn on expanded tabcomplete
# autoload -U compinit
# compinit

# ## and support some bash completion scripts too
# autoload -U bashcompinit
# bashcompinit

# ## allows $fg[white], $bg[red], $terminfo[bold]
# autoload colors zsh/terminfo
# colors
###
### TODO
###

##
## General
##
alias cl='clear'

##
## Open Tofu
##
export TOFUENV_AUTO_INSTALL=true
alias tfg='tofu get -update'
alias tfi='tofu init'
alias tfp="tofu plan -parallelism 250 -out tfplan"
alias tfip="tofu init && tofu plan -parallelism 250 -out tfplan"
alias tfa="tofu apply -parallelism 250 \"tfplan\""
alias tf-import="tofu import"
alias tf-version="tofu version"
alias tf-fmt="tofu fmt -recursive $(git rev-parse --show-toplevel)"
#alias tfs="cat \"$(find . -type d -name .terraform)/terraform.tfstate\" | jq -r '.backend.config | \"s3://\(.bucket)/\(.key)\"'"

# Set theme in ~/.oh-my-zsh/themes/
ZSH_THEME="greg-kman"

# https://github.com/wting/autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Setups up notifications with the use of bgnotify plugin
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/bgnotify
bgnotify_bell=true
bgnotify_threshold=5  # Notification threshold in seconds
function bgnotify_formatted {
  ## $1=exit_status, $2=command, $3=elapsed_time
  [ $1 -eq 0 ] && title="Success!" || title="Failure!"
  bgnotify "$title -- after $3 s" "$2";
}

function cd-gt() {
  cd $(git rev-parse --show-toplevel)
}

plugins=(alias-finder ansible autojump aws battery bgnotify brew bundler colored-man-pages colorize direnv docker docker-compose encode64 extract fzf git git-auto-fetch git-prompt gitignore golang kubectl macos node npm opentofu podman pre-commit python starship sudo tmux ubuntu vagrant web-search)
fpath=(~/.zsh-functions $fpath)
# autoload -Uz fd
# autoload -Uz iac-clean
# autoload -Uz aws-login

source "$ZSH/oh-my-zsh.sh"

if [[ $(uname) == "Darwin" ]]; then
  export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
  export PATH="/opt/homebrew/bin:$PATH"
  export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
  source "/opt/homebrew/opt/kube-ps1/share/kube-ps1.sh"
fi

eval "$(direnv hook zsh)"
eval "$(starship init zsh)"
