export SHOW_AWS_PROMPT=false
export TFENV_AUTO_INSTALL=true
export ZSH=~/.oh-my-zsh
export GOPATH=~/code/gocode
export PATH=$PATH:~/bin:~/code/gocode/bin
# autoload -U colors && colors
# autoload -U promptinit
promptinit

###
### TODO
###
# ## turn on expanded tabcomplete
# autoload -U compinit
# compinit

# ## and support some bash completion scripts too
# autoload -U bashcompinit
# bashcompinit

# ## allows $fg[white], $bg[red], $terminfo[bold]
# autoload colors zsh/terminfo
# colors
###
### TODO
###

##
## General
##
alias cl='clear'

##
## Terraform
##
alias tfg="terraform get -update"
alias tfi="terraform init"
alias tfu="terraform init -upgrade"
alias tfimp="terraform import"
alias tfp="terraform plan -parallelism 250 -out tfplan"
alias tfip="terraform init && terraform plan -parallelism 250 -out tfplan"
alias tfa="terraform apply -parallelism 250 \"tfplan\""
alias tfv="terraform version"
alias tff="terraform fmt -recursive $(git rev-parse --show-toplevel)"

# Set theme in ~/.oh-my-zsh/themes/
ZSH_THEME="greg-kman"

# https://github.com/wting/autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Setups up notifications with the use of bgnotify plugin
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/bgnotify
bgnotify_bell=true
bgnotify_threshold=5  # Notification threshold in seconds
function bgnotify_formatted {
  ## $1=exit_status, $2=command, $3=elapsed_time
  [ $1 -eq 0 ] && title="Success!" || title="Failure!"
  bgnotify "$title -- after $3 s" "$2";
}

function cd-gt() {
  cd $(git rev-parse --show-toplevel)
}

plugins=(alias-finder ansible autojump aws battery bgnotify brew bundler colored-man-pages colorize direnv docker docker-compose encode64 extract git git-auto-fetch git-prompt gitignore golang kubectl macos node npm podman pre-commit python starship sudo terraform tmux ubuntu vagrant vault vscode web-search)

source "$ZSH/oh-my-zsh.sh"

if [[ $(uname) == "Darwin" ]]; then
 export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
fi

eval "$(direnv hook zsh)"
eval "$(starship init zsh)"

